apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-sample
spec:
  ingressClassName: nginx
  rules:
  - host: nodesampleing
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: node-app-svc
              port:
                number: 8080