name: Delete knts cluster on merge/close of PR
on:
  pull_request:
    types: [closed, synchronize]
env:
  CI: false
jobs:
  Delete_and_preview:
    runs-on: 
    - self-hosted
#     - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            echo "BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - uses: zelarhq/k8s-cluster@delete
        id: k8s-master
        with:
#           version: v1.21.2-k3s1
#           size: SMALL
          name: node-${{ env.BRANCH }}
          token: ${{ secrets.KNTS_TOKEN }}
      - run: |
           ls ~/.knts
           # rm -rf ~/.knts
