name: Deploy to knts on PR
on:
  pull_request:
    types: [opened, synchronize]
env:
  CI: false
jobs:
  build_and_preview:
    runs-on: 
    - self-hosted
#     permissions:
#       pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - run: |
            echo "BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCR_PASSWORD }}
          registry: gcr.io
          project_id: klusternetes-dev
          image_name: nodejs-sample
          image_tag: latest,${{ env.BRANCH }}
      - uses: zelarhq/k8s-cluster@test
        id: k8s-master
        with:
          version: v1.21.2-k3s1
          size: SMALL
          name: node-${{ env.BRANCH }}
          token: ${{ secrets.KNTS_TOKEN }}
      - run: |
          export KUBECONFIG=~/.knts/config
          echo "INGRESS=$(kubectl config view -o jsonpath='{.clusters[].cluster.server}' | sed 's|https://vc|nodesam|g')" >>  $GITHUB_ENV
     
      - run: |
          export KUBECONFIG=~/.knts/config
          # echo "INGRESS=$(kubectl config view -o jsonpath='{.clusters[].cluster.server}' | sed 's|https://vc|nodesam|g')" >>  $GITHUB_ENV
          echo ${{ env.INGRESS }}
          sed -i 's/nodesampleing/ ${{ env.INGRESS }}/g' deployment.yaml
          kubectl apply -f ./deployment.yaml -n default --kubeconfig ~/.knts/config
          sleep 20;
          kubectl get all
          kubectl get ing
        # env: 
         # HOST_NAME: ${{ kubectl config view -o jsonpath='{.clusters[].cluster.server}' | sed 's|https://vc|nodesam|g' }}
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Service url: https://${{ env.INGRESS }}
