
name: Deploy to knts on PR
on:
  pull_request:
    types: [opened, synchronize]
env:
  CI: false
jobs:
  build_and_preview:
    runs-on: 
    - self-hosted
#     - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: gcr.io/klusternetes-dev/nodejs-sample
          tags: latest $GITHUB_SHA
          dockerfiles: |
            ./Dockerfile
      - uses: google-github-actions/setup-gcloud@v0
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCR_PASSWORD }}
          registry: gcr.io
          project_id: klusternetes-dev
          image_name: nodejs-sample
      - uses: zelarhq/k8s-cluster@main
        id: k8s-master
        with:
          version: v1.21.2-k3s1
          size: SMALL
          name: nodejs-cluster
          token: ${{ secrets.KNTS_TOKEN }}
      - name: Kubernetes Deployment
        run: |
            kubectl deploy node-app --image=gcr.io/klusternetes-dev/nodejs-sample:$GITHUB_SHA --replicas=1 
      - run: |
          kubectl get all
